{"uid":"f659eff3c61bec3b","name":"Создания юзера","fullName":"tests.test_base.test_base.TestBase#test_create_user","historyId":"b3e96d5e41d99904760a08e0ab2540a2","time":{"start":1759810593952,"stop":1759810594168,"duration":216},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\ndata\n  Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing","statusTrace":"self = <test_base.TestBase object at 0x7ff1d5f51610>\nauthentications_client = <clients.user.user_client.UserClient object at 0x7ff1d5d69e20>\n\n    @allure.title('Создания юзера')\n    def test_create_user(self, authentications_client):\n        with allure.step(\"Создание пользователя\"):\n            request_user = CreateUserSchema()\n            user = authentications_client.create_user_api(body=request_user)\n>           schema = UserSchema.model_validate_json(user.text)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\nE           data\nE             Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.11/v/missing\n\ntests/test_base/test_base.py:20: ValidationError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1759810593847,"stop":1759810593847,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_faker","time":{"start":1759810593847,"stop":1759810593904,"duration":57},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1759810593847,"stop":1759810593847,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1759810593905,"stop":1759810593905,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"authentications_client","time":{"start":1759810593905,"stop":1759810593951,"duration":46},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1759810593905,"stop":1759810593905,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auto_authorize","time":{"start":1759810593951,"stop":1759810593952,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\ndata\n  Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing","statusTrace":"self = <test_base.TestBase object at 0x7ff1d5f51610>\nauthentications_client = <clients.user.user_client.UserClient object at 0x7ff1d5d69e20>\n\n    @allure.title('Создания юзера')\n    def test_create_user(self, authentications_client):\n        with allure.step(\"Создание пользователя\"):\n            request_user = CreateUserSchema()\n            user = authentications_client.create_user_api(body=request_user)\n>           schema = UserSchema.model_validate_json(user.text)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\nE           data\nE             Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.11/v/missing\n\ntests/test_base/test_base.py:20: ValidationError","steps":[{"name":"Создание пользователя","time":{"start":1759810593952,"stop":1759810594168,"duration":216},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\ndata\n  Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing\n","statusTrace":"  File \"/home/runner/work/PetProject/PetProject/tests/test_base/test_base.py\", line 20, in test_create_user\n    schema = UserSchema.model_validate_json(user.text)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pydantic/main.py\", line 746, in model_validate_json\n    return cls.__pydantic_validator__.validate_json(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Создание юзера","time":{"start":1759810593953,"stop":1759810594167,"duration":214},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"body","value":"CreateUserSchema(name='Эммануил Терентьевич Колесников', email='uljan32@example.net', password='^)WxUZ9GG1')"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"7bf791942858e3da","name":"log","source":"7bf791942858e3da.txt","type":"text/plain","size":347}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"feature","value":"Базовый тест на создание юзера"},{"name":"parentSuite","value":"API tests"},{"name":"epic","value":"Base test"},{"name":"tag","value":"no_auto_authorize"},{"name":"suite","value":"test_base"},{"name":"subSuite","value":"TestBase"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"2436-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_base.test_base"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":3,"unknown":0,"total":4},"items":[{"uid":"2a9f8c593a4d7ce5","reportUrl":"https://MikhailLuginin.github.io/PetProject/23//#testresult/2a9f8c593a4d7ce5","status":"passed","time":{"start":1759810308223,"stop":1759810309005,"duration":782}},{"uid":"b701f0254091a7a3","reportUrl":"https://MikhailLuginin.github.io/PetProject/20//#testresult/b701f0254091a7a3","status":"passed","time":{"start":1759762499201,"stop":1759762500135,"duration":934}},{"uid":"745f2bc3e9db5c2f","reportUrl":"https://MikhailLuginin.github.io/PetProject/19//#testresult/745f2bc3e9db5c2f","status":"passed","time":{"start":1759761231472,"stop":1759761232255,"duration":783}}]},"tags":["no_auto_authorize"]},"source":"f659eff3c61bec3b.json","parameterValues":[]}